### ISSUE TITLE
Can't close discord connection

### ISSUE THREAD

**Issue by TheOneMusic** [Rapptz/discord.py#5207]
### Summary

Thank you everyone for releasing `discord.py` version 1.4 (final), you are amazing. However, with this new version, I am enable to close the discord connection with my bot. Here is a minimal reproducible example:

File: **main.py**
```python
import discord, asyncio
from discord.ext import commands

bot = commands.Bot("!")

if __name__ == "__main__":
    bot.load_extension("cogs.owner")
    bot.run(TOKEN)
```

File: **cogs/owner.py**
```python
import discord, asyncio
from discord.ext import commands

class Owner(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    @commands.is_owner()
    async def shutdown(self, ctx):
        await self.bot.close()

def setup(bot):
    bot.add_cog(Owner(bot))
```

Now when I run the `shutdown` command, the whole program just freezes (it doesn't terminate) and the fans on my computer start to spin faster. The bot still appears online but is not responding. This is weird, as everything worked alright before the update.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Gobot1234** [comment]
I think it might be beneficial if you could get the logs for this.
https://discordpy.readthedocs.io/en/latest/logging.html

**Comment by TheOneMusic** [comment]
@Gobot1234 I have used it (using my `discord.log` file), and I found semething very weird. After executing the command, I found this line: `:DEBUG:discord.gateway: Received WSMessage(type=<WSMsgType.CLOSING: 256>, data=None, extra=None)` followed by the lines: `:DEBUG:discord.gateway: Received WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)` being repeated over 7,000 times.

**Comment by Rapptz** [comment]
I couldn't reproduce this locally but I believe that https://github.com/Rapptz/discord.py/commit/5dd8e372e4a5aa3749d85f8fd2f7eb4d779512cb should fix it.

**Comment by TheOneMusic** [comment]
@Rapptz Thank you. Is there anyway I could test it?

**Comment by Gobot1234** [comment]
```sh
git clone https://github.com/Rapptz/discord.py
cd discord.py
python3 -m pip install -U .[voice]
```

**Comment by TheOneMusic** [comment]
@Gobot1234 I could install [`.voice`] (it said no matches found: `.[voice]`) so I used `.` instead. Thank you.

**Comment by TheOneMusic** [comment]
It doesn't seem to fix the issue. The bot still appears online but doesn't respond (at least the program doesn't seem to get stuck).

**Comment by Rapptz** [comment]
If the program terminates then that's the extent of what I can do.
